### ISSUE TITLE
question: builds statiques

### ISSUE THREAD

**Issue by revolunet** [cloud-pi-native/documentation#11]
Bonjour, dans le fichier "prerequisisites" on peut lire :

> La configuration de l'application se fait par son environnement (principalement par des variables d'environnements). Seuls ces éléments changent entre deux environnements : **il s'agit de la même image déployée** avec un configuration différente (pas de reconstruction pour passer d'un environnement à un autre)

Comment faire pour les applications qui sont buildées avec des informations statiques ?
(Actuellement nous avons des builds docker spécifiques selon l'environnement.)

Je pense par exemple a des apps JavaScript (ex: create-react-app) ou tout simplement des sites statiques (nginx) qui ont besoin de "build-args" différents en dev ou en prod, par exemple pour des urls sentry, matomo ou autre.
Comme ce sont des applis JavaScript, on ne peut pas changer certaines variables au runtime.

**Comment by JAubAot** [comment]
Bonjour,

 

Il est possible via le index.html de récupéré un fichier de type "config.js" généré a partir d'une configmap surchargeant les valeurs d'environnement

 

config.js
```
window.SSO_ISSUER="[https://mysso.mysso/realms/myrealm"](https://mysso.mysso/realms/myrealm%22)
window.SSO_CLIENT="myssoclientid"
```


index.html
```
<script src="/config.js"></script>
```

 
Les variables peuvent ainsi être surchargé au runtime via la configmap générant le config.js et sont ensuite accessible via window.SSO_ISSUER

**Comment by revolunet** [comment]
ok c'est un workaround possible merci
