### ISSUE TITLE
🐛 [BUG] - Rename Gitlab by GitLab 

### ISSUE THREAD

**Issue by jeanphi-baconnais** [cloud-pi-native/documentation#30]
### Description

J'ai vu plusieurs fois la notion de "Gitlab" alors qu'il s'agit de "GitLab" avec un L majuscule.

### Etapes de reproduction

```bash
1. Aller à sur https://github.com/cloud-pi-native/documentation/blob/main/docs/services/gitlab.md
```

### Captures d'écran

```bash
![DESCRIPTION](LINK.png)
```

### Définition du fini

- [ ] Le correctif est terminé
- [ ] Les tests liés à ce correctif ont été ajoutés
- [ ] La communication avec les autres équipes impliquées par ce correctif a été faite

**Comment by this-is-tobi** [comment]
fixed in #34
